-- 1. Create the support_tickets table
CREATE TABLE IF NOT EXISTS support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'open' -- 'open', 'resolved', 'closed'
);

-- 2. Add is_hidden column to listings table
ALTER TABLE listings 
ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE;

-- 3. Enable RLS on support_tickets (Optional but recommended)
ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert tickets (public submission)
CREATE POLICY "Enable insert for everyone" ON support_tickets
    FOR INSERT WITH CHECK (true);

-- Allow admins (or anyone for now if you haven't set up admin roles in DB) to read
-- For simplicity in this iteration, we might make it public read for authenticated users or just rely on service_role in backend
-- But since we are using server actions with createClient(), we act as the logged in user.
-- Let's allow authenticated users to view tickets for now to keep it simple for the admin dashboard,
-- assuming only admins will know the URL. Ideally, we'd check for a specific role.
CREATE POLICY "Enable match for authenticated users" ON support_tickets
    FOR SELECT TO authenticated USING (true);

-- Allow authenticated users to update (triage)
CREATE POLICY "Enable update for authenticated users" ON support_tickets
    FOR UPDATE TO authenticated USING (true);

-- Allow authenticated users to delete
CREATE POLICY "Enable delete for authenticated users" ON support_tickets
    FOR DELETE TO authenticated USING (true);
