-- 1. Add user_id to support_tickets to link to registered users
ALTER TABLE support_tickets 
ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id);

-- 2. Create ticket_replies table
CREATE TABLE IF NOT EXISTS ticket_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT REFERENCES support_tickets(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id), -- Who sent the reply (admin or user)
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_admin_reply BOOLEAN DEFAULT FALSE
);

-- 3. RLS for ticket_replies
ALTER TABLE ticket_replies ENABLE ROW LEVEL SECURITY;

-- Allow insert for authenticated users (both admin and user can reply)
CREATE POLICY "Enable insert for authenticated users" ON ticket_replies
    FOR INSERT TO authenticated WITH CHECK (true);

-- Allow select for authenticated users (we will filter by ownership in backend/RLS logic)
CREATE POLICY "Enable select for authenticated users" ON ticket_replies
    FOR SELECT TO authenticated USING (true);
